import { resolveBrowserUserKey } from "./identity";

/**
 * Client-side Gemini Live session (browser only).
 *
 * Owns exactly one WebSocket: browser <-> Google. Mia's server is NOT in the
 * audio path — it only mints the short-lived token (see
 * `apps/web/src/app/api/gemini-live/token/route.ts`), which is what keeps
 * `GEMINI_API_KEY` server-side (invariant 5) while still giving the browser the
 * low-latency direct connection Google's docs recommend.
 *
 * Protocol facts (verified against
 * https://ai.google.dev/gemini-api/docs/live-api/get-started-websocket,
 * page last updated 2026-09-15):
 *   - the client URL is the **Constrained** method, `?access_token=`;
 *   - the first frame MUST be `setup` and the model id carries a `models/` prefix;
 *   - audio in is raw 16-bit LE PCM at 16 kHz, base64, in `realtimeInput.audio`;
 *   - audio out is raw 16-bit LE PCM at 24 kHz, base64, in
 *     `serverContent.modelTurn.parts[].inlineData.data`;
 *   - the user's speech arrives as `serverContent.inputTranscription.text`
 *     (only when `inputAudioTranscription` is requested in `setup`);
 *   - Gemini's own speech arrives as `serverContent.outputTranscription.text`.
 *
 * Deliberately NOT a full `AIProvider` implementation: the existing
 * `ConversationManager`/`AutoTurnManager` path is turn-based (MediaRecorder ->
 * Whisper -> LLM -> TTS) and Gemini Live is duplex and self-turn-taking.
 * Squeezing it through that machinery would fight it, so this is wired as its
 * own voice mode in the console instead.
 */

/** Live websocket endpoint (the client-side, ephemeral-token method). */
const LIVE_WS_BASE =
  "wss://generativelanguage.googleapis.com/ws/google.ai.generativelanguage.v1beta.GenerativeService.BidiGenerateContentConstrained";

/** What the UI needs to know about the session. */
export type GeminiLiveStatus =
  | "idle"
  | "connecting"
  | "ready"
  | "error"
  | "closed";

export type GeminiLiveEvent =
  /** Raw PCM out, already base64-decoded, at {@link LIVE_OUTPUT_SAMPLE_RATE}. */
  | { type: "audio"; pcm: Uint8Array }
  /** Streaming transcript of the USER's speech. */
  | { type: "input_transcript"; text: string; final: boolean }
  /** Streaming transcript of GEMINI's speech. */
  | { type: "output_transcript"; text: string; final: boolean }
  /** Gemini started/finished a turn — used to drive the orb's state. */
  | { type: "speaking"; speaking: boolean }
  /** The model interrupted itself (user barge-in took effect server-side). */
  | { type: "interrupted" }
  /** Anything the model said as plain text (not speech). */
  | { type: "text"; text: string }
  /**
   * Connected, but the server has not sent a SINGLE frame yet.
   *
   * A separate signal is needed because "not talking" and "not connected" are
   * different problems with different fixes, and a spinner cannot express
   * either. Deliberately narrow: it may only fire before the first frame, because
   * a duplex session is silent between turns BY DESIGN and a notice then would be
   * nagging a perfectly healthy session.
   */
  | { type: "stalled"; message: string }
  | { type: "status"; status: GeminiLiveStatus; detail?: string }
  | { type: "error"; message: string }
  /**
   * The model invoked one or more declared tools. The caller MUST answer every
   * call with `sendToolResponse`, even on failure: Live tool calls are
   * synchronous (measured 2026-09-30 — the model is completely silent while
   * waiting), so an unanswered call is not a skipped tool, it is a hung
   * conversation.
   */
  | { type: "tool_call"; calls: LiveToolCall[] };

export type GeminiLiveListener = (event: GeminiLiveEvent) => void;

/** One tool invocation from the model: `toolCall.functionCalls` on the wire. */
export interface LiveToolCall {
  /** Present when the model supplied one; generated by the caller otherwise. */
  id: string;
  name: string;
  /** Decoded `args` object; `{}` when the model sent none or malformed JSON. */
  args: Record<string, unknown>;
}

/**
 * Strip the 🌸 signature flower from Live transcripts.
 *
 * Live-only: the persona asks for 🌸 in *text* replies, but a Live turn is
 * voice — the model speaks the transcript, and an emoji in the spoken line
 * makes the audio stutter (owner report 2026-09-30). The chat path keeps its
 * flower; only the Live transcript path calls this.
 *
 * Pure and exported so the transcript accumulation and the memory write-back
 * share one definition. Collapses the gap the flower leaves so words never
 * glue together and never double-space.
 */
export function stripLiveFlower(text: string): string {
  return text.replace(/🌸\uFE0F?/g, "").replace(/[ \t]{2,}/g, " ");
}

/** A Gemini `functionDeclarations` entry, as served by our token route. */
export interface LiveToolDeclaration {
  name: string;
  description: string;
  parameters?: unknown;
}

/** One tool result back to the model: `toolResponse.functionResponses`. */
export interface LiveToolResult {
  id: string;
  name: string;
  /** Plain-text outcome (or an `Error: ...` string); the model speaks from it. */
  result: string;
}

export interface GeminiLiveOptions {
  /** System instruction. The persona is injected here by the caller. */
  systemInstruction?: string;
  /** Tool declarations from our token route; omitted when the server sent none. */
  tools?: LiveToolDeclaration[];
  /**
   * Prebuilt voice for the session (e.g. "Leda"). Server value wins when the
   * token route returns one; omitted entirely when neither side sets it, so a
   * session without voice config behaves exactly like before.
   */
  voiceName?: string;
  /** Ask the API to transcribe the user's speech (needed for subtitles). */
  enableInputTranscription?: boolean;
  /** Ask the API to transcribe Gemini's speech. */
  enableOutputTranscription?: boolean;
}

export interface StartResult {
  ok: boolean;
  /** Present when `ok` is false; already safe to show to a user. */
  error?: string;
  /**
   * Why the start settled. `"setup-complete"` is the documented path; the other
   * two exist because the deployed API can stay silent forever and a start that
   * never resolves is the bug this whole block was added to prevent.
   */
  via?: "setup-complete" | "grace" | "timeout";
}

/**
 * Grace period after the setup frame is written.
 *
 * The socket being open and our own frame being written IS a connection fact we
 * can observe without the server's permission. Waiting for `setupComplete` alone
 * is what made the UI sit on "Menyambung..." forever, so a bounded grace makes
 * the promise settle on a fact we actually hold. An error or a close inside the
 * window still wins, because those are real failures.
 */
const SETTLE_GRACE_MS = 2_500;

/** Hard ceiling on `start()`. A start can never hang, whatever the server does. */
const START_TIMEOUT_MS = 15_000;

/**
 * How long a connected session may go without the server sending ANY frame.
 *
 * Only ever armed before the first frame (see `armStallWatchdog`). It is
 * deliberately not an error: the socket is open and audio may start at any
 * moment, so the honest thing is a distinct notice, not a red failure the user
 * has to dismiss. The window is generous because a cold Live session can take a
 * while to produce its first frame, and a notice that fires on a merely slow
 * connection is worse than no notice.
 */
const FIRST_FRAME_WATCHDOG_MS = 20_000;

/**
 * Decode one WebSocket frame into text.
 *
 * MEASURED against the live API 2026-09-30 with the owner's key: Google sends
 * EVERY frame as **binary** — including `setupComplete`, which is a
 * JSON-encoded binary frame like all the rest. That is why an earlier version of
 * this client believed the API "went silent after `setup`": the browser's
 * `WebSocket.binaryType` defaults to `"blob"`, so `String(event.data)` produced
 * the literal `"[object Blob]"`, `JSON.parse` threw, and a `catch` written to
 * "keep the session alive" quietly discarded every server frame — including the
 * handshake. The UI then sat on "Menyambung..." forever with no error anywhere.
 *
 * Pure and exported so this exact decoding is provable without a socket.
 *
 * Returns `""` for anything undecodable, including a `Blob`: reading one needs
 * an async API, and it cannot occur once `binaryType` is set to `"arraybuffer"`
 * (which `start()` does immediately after constructing the socket).
 */
export function frameText(data: unknown): string {
  if (typeof data === "string") return data;
  if (data instanceof ArrayBuffer) return new TextDecoder().decode(new Uint8Array(data));
  if (ArrayBuffer.isView(data)) {
    const view = new Uint8Array(data.buffer as ArrayBuffer, data.byteOffset, data.byteLength);
    return new TextDecoder().decode(view);
  }
  return "";
}

/**
 * A single Gemini Live duplex session.
 *
 * Not reusable after `stop()`: ephemeral tokens are single-use, so a restart
 * mints a fresh one. That is intentional — a stale socket is the classic source
 * of "the bot went quiet after ten minutes".
 */
export class GeminiLiveSession {
  private ws: WebSocket | null = null;
  private listeners = new Set<GeminiLiveListener>();
  private status: GeminiLiveStatus = "idle";
  private closing = false;
  private model = "";
  /**
   * Mic mute for the session. While set, `sendAudioFrame` drops frames instead
   * of sending them: the socket stays open and the server hears silence, so a
   * mute never ends the conversation. This exists because the UI presents the
   * mic button as mute (MicOff icon while live) — and an earlier version of
   * this code actually STOPPED the session there, which is exactly the bug the
   * owner reported ("tekan mic malah mengakhiri obrolan").
   */
  private audioMuted = false;
  /** Bounded grace after the setup frame, so `start()` always settles. */
  private settleTimer: ReturnType<typeof setTimeout> | null = null;
  /** Hard ceiling on `start()`, so a dead socket can never hang the UI. */
  private startTimer: ReturnType<typeof setTimeout> | null = null;
  /** Fires when a ready session has produced nothing at all. */
  private stallTimer: ReturnType<typeof setTimeout> | null = null;
  /** Server frames seen this session; the watchdog only fires while this is 0. */
  private frameCount = 0;
  /**
   * Per-turn transcript buffers. Transcription events carry INCREMENTAL chunks,
   * so the lib accumulates them here and always emits the whole turn so far —
   * overwriting per event is what made subtitles look "cut off mid-sentence".
   * Reset when a new turn starts after a `turnComplete`, never mid-turn.
   */
  private inputBuf = "";
  private outputBuf = "";
  private turnClosed = false;

  constructor(private readonly options: GeminiLiveOptions = {}) {}

  get currentStatus(): GeminiLiveStatus {
    return this.status;
  }

  on(fn: GeminiLiveListener): () => void {
    this.listeners.add(fn);
    return () => this.listeners.delete(fn);
  }

  /**
   * Mint a token, open the socket, and complete the `setup` handshake.
   *
   * Never throws: a failure is reported through the returned result AND an
   * `error` event, because the caller's job is to fall back to the Groq
   * pipeline, not to handle an exception.
   */
  async start(): Promise<StartResult> {
    if (this.ws) return { ok: true };
    this.closing = false;
    this.setStatus("connecting");

    let token: string;
    let model: string;
    let serverInstruction: string;
    let serverTools: LiveToolDeclaration[];
    let serverVoice: string;
    try {
      // Who is speaking, so the server loads the RIGHT persona. The token
      // route reads `x-mia-user` and falls back to the DEFAULT persona when it
      // is absent — and the default has none of the owner's facts (measured
      // 2026-09-30: every Live turn spoke as generic Mia — no city, no cat).
      // Resolved through the same override the chat path uses, so a stale
      // browser value can never fork a second identity here either.
      let userHeader: Record<string, string> = {};
      try {
        if (typeof window !== "undefined") {
          userHeader = { "x-mia-user": resolveBrowserUserKey(window.localStorage.getItem("voice-ai.user")) };
        }
      } catch {
        // No storage in this environment (private mode, tests): the header
        // stays absent and the server falls back to the default persona.
      }
      const res = await fetch("/api/gemini-live/token", { method: "POST", headers: userHeader });
      const json = (await res.json().catch(() => ({}))) as {
        token?: string;
        model?: string;
        systemInstruction?: string;
        tools?: LiveToolDeclaration[];
        voice?: string;
        error?: string;
      };
      if (!res.ok || !json.token) {
        const message = json.error ?? `Gemini Live is unavailable (HTTP ${res.status}).`;
        this.emit({ type: "error", message });
        this.setStatus("error", message);
        return { ok: false, error: message };
      }
      token = json.token;
      // The server may pin a different model; fall back to the documented one.
      model = json.model ?? "models/gemini-3.8-live";
      // The persona is loaded server-side and returned here, because the
      // deployed `auth_tokens` API rejects `liveConnectConstraints` and cannot
      // pin it. Server value wins over a caller's own hint so Mia's identity
      // cannot be replaced by a stale client default.
      serverInstruction = json.systemInstruction ?? this.options.systemInstruction ?? "";
      // Tool declarations come from the same server response (built from the
      // live registry by `liveTools.ts`), so the client can never declare a
      // tool the server would not execute. Caller hint wins only when the
      // server sent none.
      serverTools =
        (Array.isArray(json.tools) ? json.tools : null) ?? this.options.tools ?? [];
      // Voice follows the same precedence as the persona: the server pins it
      // (env `GEMINI_LIVE_VOICE`), the caller's hint only fills the gap.
      serverVoice =
        (typeof json.voice === "string" && json.voice.trim() ? json.voice.trim() : "") ||
        this.options.voiceName ||
        "";
    } catch (err) {
      const message = `Could not reach the Gemini Live token route: ${
        err instanceof Error ? err.message : String(err)
      }`;
      this.emit({ type: "error", message });
      this.setStatus("error", message);
      return { ok: false, error: message };
    }

    this.model = model;
    this.frameCount = 0;

    return new Promise<StartResult>((resolve) => {
      let settled = false;
      const clearTimers = () => {
        if (this.settleTimer) clearTimeout(this.settleTimer);
        if (this.startTimer) clearTimeout(this.startTimer);
        this.settleTimer = null;
        this.startTimer = null;
      };
      const finish = (result: StartResult) => {
        if (settled) return;
        settled = true;
        clearTimers();
        resolve(result);
      };

      // Absolute ceiling: whatever the socket does, `start()` resolves.
      this.startTimer = setTimeout(() => {
        const message =
          "The Gemini Live connection did not come up within 15 seconds (this is Google's side, not your microphone).";
        this.emit({ type: "error", message });
        this.setStatus("error", message);
        finish({ ok: false, error: message, via: "timeout" });
      }, START_TIMEOUT_MS);

      let socket: WebSocket;
      try {
        socket = new WebSocket(`${LIVE_WS_BASE}?access_token=${encodeURIComponent(token)}`);
      } catch (err) {
        const message = `Could not open the Gemini Live socket: ${
          err instanceof Error ? err.message : String(err)
        }`;
        this.emit({ type: "error", message });
        this.setStatus("error", message);
        finish({ ok: false, error: message });
        return;
      }
      this.ws = socket;

      // MUST be set before the first frame lands. Google sends every Live frame
      // as binary (measured 2026-09-30) and the browser default is `"blob"`,
      // which cannot be decoded synchronously — see `frameText`.
      socket.binaryType = "arraybuffer";

      socket.onopen = () => {
        this.send({
          setup: {
            model: this.model,
            // MEASURED against the live API 2026-09-29: `responseModalities` is
            // NOT a top-level `setup` field — the socket closes with
            // `Unknown name "responseModalities" at 'setup'`. Inside
            // `generationConfig` it is accepted. The docs show it at the top
            // level; the deployed API is narrower than the docs.
            generationConfig: {
              responseModalities: ["AUDIO"],
              // Prebuilt voice (docs: Live shares the TTS voice pool, e.g.
              // "Leda"). Inside generationConfig — the deployed API rejects
              // top-level fields it does not know (measured with
              // responseModalities), so this stays next to the field that is
              // proven accepted. Omitted when unset: a voiceless setup is the
              // old behavior, byte for byte.
              ...(serverVoice
                ? {
                    speechConfig: {
                      voiceConfig: { prebuiltVoiceConfig: { voiceName: serverVoice } },
                    },
                  }
                : {}),
            },
            // `sessionResumption` is accepted as a top-level field (measured),
            // and lets the browser reconnect with the same token after a drop.
            sessionResumption: {},
            // Affective dialog NOT enabled: `enableAffectiveDialog: true` was
            // tried 2026-10-01 and every session died on mic-press with "The
            // Gemini Live session ended" — the Constrained endpoint
            // (ephemeral-token variant) rejects it even though the docs list
            // it for the full endpoint. Same class as the top-level
            // `responseModalities` rejection. Laughter/tone stays prompt-only.
            // Do NOT re-add without a live session-start proof.
            // Let the user finish thinking: the server ends their turn after
            // this much silence, and the default (~800 ms) cuts breathing
            // pauses mid-sentence. 1200 ms keeps answers snappy while giving
            // clause boundaries room (owner 2026-10-01: natural overlap).
            // If the deployed API ever rejects this field, delete it — the
            // session must never fail to start over a tuning knob.
            realtimeInputConfig: {
              automaticActivityDetection: { silenceDurationMs: 1200 },
            },
            ...(serverInstruction
              ? { systemInstruction: { parts: [{ text: serverInstruction }] } }
              : {}),
            // MEASURED against the live API 2026-09-30: `tools` is accepted as
            // a TOP-LEVEL `setup` field (unlike `responseModalities`, which the
            // socket rejects there). Each entry wraps Gemini function
            // declarations; a model call arrives as top-level `toolCall` and
            // MUST be answered, or the synchronous call hangs the turn.
            ...(serverTools.length ? { tools: [{ functionDeclarations: serverTools }] } : {}),
            ...(this.options.enableInputTranscription !== false
              ? { inputAudioTranscription: {} }
              : {}),
            ...(this.options.enableOutputTranscription !== false
              ? { outputAudioTranscription: {} }
              : {}),
          },
        });

        // The socket is open and our frame is written — a fact we hold,
        // independent of whether the server answers. Arming this bounded grace
        // means the UI can never sit on "Menyambung..." forever even if the
        // server never replies. `setupComplete` (measured: it DOES arrive, as a
        // binary frame) still wins the race and reports the accurate `via`.
        this.settleTimer = setTimeout(() => {
          if (settled) return;
          this.setStatus("ready");
          this.armStallWatchdog();
          finish({ ok: true, via: "grace" });
        }, SETTLE_GRACE_MS);
      };

      socket.onmessage = (event) => {
        // `frameText`, NOT `String(event.data)`: Google sends binary frames, and
        // `String(blob)` is literally "[object Blob]" (see the helper's doc).
        const raw = frameText(event.data);
        if (raw) this.handleMessage(raw, finish);
      };

      socket.onerror = () => {
        // The browser deliberately gives no detail here; a generic message plus
        // the status change is the most actionable thing we can say.
        if (this.closing) return;
        const message = "The Gemini Live connection failed.";
        this.clearWatchdogs();
        this.emit({ type: "error", message });
        this.setStatus("error", message);
        finish({ ok: false, error: message });
      };

      socket.onclose = () => {
        this.ws = null;
        // A close is a fact too: it must not leave a silence notice pending.
        this.clearWatchdogs();
        if (this.closing) {
          this.setStatus("closed");
          return;
        }
        // A server-initiated close means the token expired or the session was
        // cut. Say so instead of pretending the mic is still live.
        this.setStatus("closed", "The Gemini Live session ended.");
      };
    });
  }

  /** Send one 16 kHz PCM frame. Silently ignored when not connected. */
  sendAudioFrame(pcm: Uint8Array, base64: string): void {
    // Muted: hear nothing, end nothing. Dropping here (not by stopping the
    // capture) keeps the mic permission/stream alive so unmuting is instant.
    if (this.audioMuted) return;
    if (!this.ws || this.ws.readyState !== WebSocket.OPEN) return;
    this.send({
      realtimeInput: {
        audio: { data: base64, mimeType: "audio/pcm;rate=16000" },
      },
    });
    void pcm; // Kept in the signature so callers cannot forget the raw bytes.
  }

  /** Inject text as if the user had said it. */
  sendText(text: string): void {
    if (!text.trim()) return;
    this.send({ realtimeInput: { text } });
  }

  /**
   * Answer the model's tool calls. One entry per call, in any order — but
   * EVERY call must be answered, even when execution failed: Live tool calls
   * are synchronous and the model stays silent until each one has a result.
   * Results SHOULD already be strings; anything else is JSON-encoded.
   */
  sendToolResponse(results: LiveToolResult[]): void {
    if (!results.length) return;
    this.send({
      toolResponse: {
        functionResponses: results.map((r) => ({
          id: r.id,
          name: r.name,
          response: { result: r.result },
        })),
      },
    });
  }

  /**
   * Stop Gemini mid-sentence — locally.
   *
   * Deliberately sends NOTHING over the socket: `{interrupt: true}` is not a
   * valid `BidiGenerateContentClientMessage` field, and the deployed API
   * closes the session on unknown top-level fields (owner 2026-10-01: every
   * local barge-in ended with "The Gemini Live session ended"). Interruption
   * is achieved by silencing locally (the caller fades/drops) while the mic
   * keeps streaming — the server yields to sustained user speech on its own
   * VAD, or the duck-hold covers it. The emits below keep UI/orb/memory
   * consistent, and clear the local player like before.
   */
  interrupt(): void {
    this.emit({ type: "interrupted" });
    this.emit({ type: "speaking", speaking: false });
  }

  /**
   * Mute or unmute the mic WITHOUT touching the session. Muting drops
   * outgoing frames (the server hears silence); the socket, the token and
   * the conversation all survive it.
   */
  setAudioMuted(muted: boolean): void {
    this.audioMuted = muted;
  }

  /** Whether outgoing audio is currently dropped. */
  get isAudioMuted(): boolean {
    return this.audioMuted;
  }

  /** Close the socket. Safe to call repeatedly. */
  stop(): void {
    this.closing = true;
    this.clearWatchdogs();
    try {
      this.ws?.close();
    } catch {
      // Already closing.
    }
    this.ws = null;
    this.setStatus("closed");
  }

  /** Drop every pending timer so a stopped session can never fire a notice. */
  private clearWatchdogs(): void {
    if (this.settleTimer) clearTimeout(this.settleTimer);
    if (this.startTimer) clearTimeout(this.startTimer);
    if (this.stallTimer) clearTimeout(this.stallTimer);
    this.settleTimer = null;
    this.startTimer = null;
    this.stallTimer = null;
  }

  private send(payload: unknown): void {
    if (!this.ws || this.ws.readyState !== WebSocket.OPEN) return;
    this.ws.send(JSON.stringify(payload));
  }

  /** Parse one server frame and fan it out. Never throws. */
  private handleMessage(raw: string, finish: (r: StartResult) => void): void {
    let msg: Record<string, unknown>;
    try {
      msg = JSON.parse(raw) as Record<string, unknown>;
    } catch {
      return; // A non-JSON frame is not actionable; keep the session alive.
    }

    // Count EVERY decoded frame, the handshake included, BEFORE branching. A
    // duplex session is silent between turns by design, so the "no frames yet"
    // notice is only honest until the server has proven it is talking at all.
    this.noteFrame();

    if (msg.setupComplete) {
      if (this.settleTimer) clearTimeout(this.settleTimer);
      this.settleTimer = null;
      this.setStatus("ready");
      this.armStallWatchdog();
      finish({ ok: true, via: "setup-complete" });
      return;
    }

    if (msg.error) {
      const detail =
        (msg.error as { message?: string } | undefined)?.message ?? "Gemini Live reported an error.";
      this.emit({ type: "error", message: detail });
      this.setStatus("error", detail);
      return;
    }

    if (msg.interrupted) {
      this.emit({ type: "interrupted" });
      this.emit({ type: "speaking", speaking: false });
      return;
    }

    // Tool calls arrive as a TOP-LEVEL `toolCall` frame (measured 2026-09-30:
    // `toolCall.functionCalls[]` with `name`, `args` and `id`), NOT inside
    // `serverContent` — so this branch must precede the early return below.
    // Malformed entries are dropped, but a frame with at least one usable
    // call is always emitted: answering is mandatory, judging is the caller's.
    const toolCall = msg.toolCall as
      | { functionCalls?: Array<{ name?: unknown; args?: unknown; id?: unknown }> }
      | undefined;
    if (Array.isArray(toolCall?.functionCalls)) {
      const calls: LiveToolCall[] = [];
      for (const [index, fc] of toolCall.functionCalls.entries()) {
        if (!fc || typeof fc.name !== "string" || !fc.name) continue;
        let args: Record<string, unknown> = {};
        if (fc.args && typeof fc.args === "object" && !Array.isArray(fc.args)) {
          args = fc.args as Record<string, unknown>;
        }
        calls.push({
          id: typeof fc.id === "string" && fc.id ? fc.id : `live-${index}`,
          name: fc.name,
          args,
        });
      }
      if (calls.length) this.emit({ type: "tool_call", calls });
      return;
    }

    const serverContent = msg.serverContent as
      | {
          modelTurn?: { parts?: Array<{ inlineData?: { data?: string }; text?: string }> };
          inputTranscription?: { text?: string };
          outputTranscription?: { text?: string };
          turnComplete?: boolean;
        }
      | undefined;
    if (!serverContent) return;

    if (typeof serverContent.inputTranscription?.text === "string") {
      this.emit({
        type: "input_transcript",
        text: this.appendTranscript("input", serverContent.inputTranscription.text),
        final: false,
      });
    }
    if (typeof serverContent.outputTranscription?.text === "string") {
      this.emit({
        type: "output_transcript",
        text: this.appendTranscript("output", serverContent.outputTranscription.text),
        final: false,
      });
    }

    let sawAudio = false;
    for (const part of serverContent.modelTurn?.parts ?? []) {
      if (part.inlineData?.data) {
        sawAudio = true;
        this.emit({ type: "audio", pcm: this.decode(part.inlineData.data) });
      } else if (part.text) {
        this.emit({ type: "text", text: part.text });
      }
    }
    if (sawAudio) this.emit({ type: "speaking", speaking: true });
    if (serverContent.turnComplete) {
      // The turn is over but the words stay on screen: the NEXT transcription
      // starts fresh (see appendTranscript), it is never wiped here, so the
      // user can still read what was just said.
      this.turnClosed = true;
      this.emit({ type: "speaking", speaking: false });
    }
  }

  /**
   * Append one incremental transcription chunk to the current turn's buffer
   * and return the whole turn so far. A new turn after a `turnComplete`
   * starts empty; chunks join with a space only when neither side supplies
   * one, so words never glue together and never double-space.
   */
  private appendTranscript(side: "input" | "output", chunk: string): string {
    if (this.turnClosed) {
      this.inputBuf = "";
      this.outputBuf = "";
      this.turnClosed = false;
    }
    // Live is voice: the 🌸 signature flower the persona asks for in text
    // replies would be spoken here and stutters the audio (owner 2026-09-30),
    // so it never reaches the transcript, the subtitles, or the memory
    // write-back. A flower-only chunk appends nothing.
    const clean = stripLiveFlower(chunk);
    if (!clean.trim()) return side === "input" ? this.inputBuf : this.outputBuf;
    const buf = side === "input" ? this.inputBuf : this.outputBuf;
    const next = !buf ? clean : /[\s(>"'\-–—]$/.test(buf) || /^[\s.,!?;:)"'\-–—]/.test(clean) ? buf + clean : `${buf} ${clean}`;
    if (side === "input") this.inputBuf = next;
    else this.outputBuf = next;
    return next;
  }

  /** base64 -> bytes, tolerant of a malformed frame. */
  private decode(data: string): Uint8Array {
    try {
      const binary = atob(data);
      const out = new Uint8Array(binary.length);
      for (let i = 0; i < binary.length; i += 1) out[i] = binary.charCodeAt(i);
      return out;
    } catch {
      return new Uint8Array(0);
    }
  }

  private setStatus(status: GeminiLiveStatus, detail?: string): void {
    this.status = status;
    this.emit({ type: "status", status, detail });
  }

  /**
   * Count a decoded server frame and disarm the "no frames yet" notice.
   *
   * The handshake counts too: `setupComplete` is proof the server is talking, so
   * counting it is what stops the notice from firing on a healthy session that
   * simply has not been spoken to yet.
   */
  private noteFrame(): void {
    this.frameCount += 1;
    if (this.stallTimer) {
      clearTimeout(this.stallTimer);
      this.stallTimer = null;
    }
  }

  /**
   * Announce a session that received no frame at all, without killing it.
   *
   * Emitted as its own event rather than an `error` on purpose: the socket is
   * still open, so a red failure the user has to dismiss would be a lie about
   * the state. Armed ONLY while `frameCount === 0` — see {@link FIRST_FRAME_WATCHDOG_MS}
   * for why a longer silence is not evidence of anything.
   */
  private armStallWatchdog(): void {
    if (this.stallTimer) clearTimeout(this.stallTimer);
    this.stallTimer = null;
    if (this.frameCount > 0 || this.closing) return;
    this.stallTimer = setTimeout(() => {
      this.stallTimer = null;
      if (this.frameCount > 0 || this.closing) return;
      this.emit({
        type: "stalled",
        message:
          "Sudah tersambung, tapi belum ada balasan apa pun dari Google. Kalau kamu memang belum bicara, itu normal — kalau sudah bicara dan tetap sunyi, tutup lalu buka Live lagi, atau pakai mode Groq.",
      });
    }, FIRST_FRAME_WATCHDOG_MS);
  }

  private emit(event: GeminiLiveEvent): void {
    for (const fn of this.listeners) {
      try {
        fn(event);
      } catch {
        // One bad listener must not kill the audio stream.
      }
    }
  }
}

/**
 * Persist one completed Live turn into today's daily memory. Fire-and-forget
 * by contract: returns whether the server confirmed the write, but NEVER
 * throws and NEVER blocks — losing one turn's note must not disturb a voice
 * session. Empty turns (both sides blank) skip the network entirely.
 *
 * `fetchImpl` exists so tests can assert URL, header and body without a
 * server; production passes the global fetch.
 */
export async function saveLiveTurnToMemory(
  heard: string,
  said: string,
  userHeader: Record<string, string>,
  fetchImpl: typeof fetch = fetch
): Promise<boolean> {
  if (!heard.trim() && !said.trim()) return false;
  try {
    const res = await fetchImpl("/api/gemini-live/memory", {
      method: "POST",
      headers: { "Content-Type": "application/json", ...userHeader },
      body: JSON.stringify({ heard: heard.slice(0, 2_000), said: said.slice(0, 2_000) }),
    });
    if (!res.ok) return false;
    const json = (await res.json().catch(() => ({}))) as { saved?: unknown };
    return json.saved === true;
  } catch {
    return false;
  }
}
